---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "lohhla"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::lohhla=20171108"
